### ISSUE TITLE
error after creating username

### ISSUE THREAD

**Issue by alpfundi** [rajatkantinandi/React-Native-ChatApp#1]
I cloned the repo, changed the credentials. I can see new user created in Pusher.
Then I get this error:

TypeError: TypeError: undefined is not an object (evaluating 'theme.label')

This error is located at:
    in HeaderTitle (at Header.tsx:224)
    in RCTView (at View.js:44)
    in AnimatedComponent (at Header.tsx:535)
    in RCTView (at View.js:44)
    in RCTView (at View.js:44)
    in RCTView (at View.js:44)
    in AnimatedComponent (at react-native-safe-area-view/index.js:163)
    in SafeView (at withOrientation.js:54)
    in withOrientation (at Header.tsx:726)
    in RCTView (at View.js:44)
    in AnimatedComponent (at Header.tsx:718)
    in Header (at withOrientation.js:30)
    in withOrientation (at StackViewLayout.tsx:226)
    in RCTView (at View.js:44)
    in RCTView (at View.js:44)
    in AnimatedComponent (at StackViewLayout.tsx:383)
    in Handler (at StackViewLayout.tsx:376)
    in StackViewLayout (at withOrientation.js:30)
    in withOrientation (at StackView.tsx:104)
    in RCTView (at View.js:44)
    in Transitioner (at StackView.tsx:41)
    in StackView (at createNavigator.js:80)
    in Navigator (at createKeyboardAwareNavigator.js:12)
    in KeyboardAwareNavigator (at SceneView.js:9)
    in SceneView (at SwitchView.js:12)
    in SwitchView (at createNavigator.js:80)
    in Navigator (at createAppContainer.js:430)
    in NavigationContainer (at App.js:93)
    in App (at withExpoRoot.js:22)
    in RootErrorBoundary (at withExpoRoot.js:21)
    in ExpoRootComponent (at renderApplication.js:34)
    in RCTView (at View.js:44)
    in RCTView (at View.js:44)
    in AppContainer (at renderApplication.js:33)

This error is located at:
    in NavigationContainer (at App.js:93)
    in App (at withExpoRoot.js:22)
    in RootErrorBoundary (at withExpoRoot.js:21)
    in ExpoRootComponent (at renderApplication.js:34)
    in RCTView (at View.js:44)
    in RCTView (at View.js:44)
    in AppContainer (at renderApplication.js:33)`

**Comment by rajatkantinandi** [comment]
I will look into the wrapper backend console..
Thanks for trying out this repo.

**Comment by rajatkantinandi** [comment]
Anyway there is no component called Header.tsx & I am not using typescript in this project.
How did you get this?
Did you create a custom component yourself or it is something from react-native side?
I just tried Signing up & it worked fine for me..

**Comment by alpfundi** [comment]
I believe those files are in react-navigation.
The live version on Expo seems unaffected. It works perfectly on my android phone with Expo link.
I just erased node_modules and ran Yarn again, same errors come back.
I'll try to upgrade expo sdk

**Comment by alpfundi** [comment]
Looks like some versions of react-navigation was causing this issue.
Issue resolved by upgrading app to expo sdk34.
I also had to update a few libraries such as expo-permissions and expo-asset as they've been removed from expo.
